- name: Create Grafana Service Account, API Token, and Add Prometheus Data Source
  hosts: localhost
  become: true

  vars:
    grafana_service_account_name: "my-service-account" # Service account name
    grafana_service_account_role: "Admin"              # Service account role
    grafana_api_token_name: "my-api-token"             # API token name
    grafana_admin_user: "admin"                        # Grafana admin username
    grafana_admin_password: "admin"                    # Grafana admin password
    grafana_base_url: "http://public_ip:3000"          # Grafana base URL
    prometheus_url: "http://public_ip:9090"            # Prometheus server URL

  tasks:

    # 2. Create service account
    - name: Create service account
      uri:
        url: "{{ grafana_base_url }}/api/serviceaccounts"
        method: POST
        headers:
          Content-Type: "application/json"
          Authorization: "Basic {{ (grafana_admin_user + ':' + grafana_admin_password) | b64encode }}"
        body: |
          {
            "name": "{{ grafana_service_account_name }}",
            "role": "{{ grafana_service_account_role }}"
          }
        body_format: json
        status_code: 200,201
      register: service_account_response

    - name: Debug service account response
      debug:
        msg: "{{ service_account_response }}"

    # 3. Create API token for service account
    - name: Create API token for service account
      uri:
        url: "{{ grafana_base_url }}/api/serviceaccounts/{{ service_account_response.json.id }}/tokens"
        method: POST
        headers:
          Content-Type: "application/json"
          Authorization: "Basic {{ (grafana_admin_user + ':' + grafana_admin_password) | b64encode }}"
        body: |
          {
            "name": "{{ grafana_api_token_name }}"
          }
        body_format: json
        status_code: 200,201
      register: api_token_response

    - name: Debug API token response
      debug:
        msg: "{{ api_token_response.json | to_nice_json }}"

    # 4. Add Prometheus data source using the API token
    - name: Add Prometheus data source
      uri:
        url: "{{ grafana_base_url }}/api/datasources"
        method: POST
        headers:
          Content-Type: "application/json"
          Authorization: "Bearer {{ api_token_response.json.key }}"
        body: |
          {
            "name": "Prometheus",
            "type": "prometheus",
            "url": "{{ prometheus_url }}",
            "access": "proxy",
            "isDefault": true
          }
        body_format: json
        status_code: 200
      register: datasource_response

    - name: Debug data source response
      debug:
        msg: "{{ datasource_response }}"
