---
- name: Setup Ansible, Prometheus, and Grafana on Control VM
  hosts: localhost
  become: true
  tasks:

    # Install Ansible
    - name: Install Ansible
      apt:
        name: ansible
        state: present
      when: ansible_facts.packages is not defined or ansible_facts.packages['ansible'] is not defined

    # Create ansible user
    - name: Create ansible user
      user:
        name: ansible
        shell: /bin/bash
        state: present
        create_home: yes

    # Give ansible user sudo privileges
    - name: Add ansible user to sudo group
      user:
        name: ansible
        groups: sudo
        append: yes

    # Generate SSH key for ansible user
    - name: Create SSH key for ansible user
      ansible.builtin.openssh_keypair:
        path: "/home/ansible/.ssh/id_rsa"
        owner: ansible
        group: ansible
        mode: '0600'
      become: yes

    # Set up passwordless SSH access for ansible user
    - name: Setup passwordless SSH access for ansible user
      authorized_key:
        user: ansible
        state: present
        key: "{{ lookup('file', '/home/ansible/.ssh/id_rsa.pub') }}"
      become: yes

    # Download Prometheus
    - name: Download Prometheus
      get_url:
        url: "https://github.com/prometheus/prometheus/releases/download/v2.51.2/prometheus-2.51.2.linux-amd64.tar.gz"
        dest: "/tmp/prometheus.tar.gz"
        mode: '0644'

    # Extract Prometheus tarball
    - name: Extract Prometheus tarball
      unarchive:
        src: "/tmp/prometheus.tar.gz"
        dest: "/tmp/"
        remote_src: yes

    # Move Prometheus binaries to /usr/local/bin/
    - name: Move Prometheus binaries
      command: mv /tmp/prometheus-2.51.2.linux-amd64/{{ item }} /usr/local/bin/
      with_items:
        - prometheus
        - promtool
      become: yes

    # Create Prometheus system user
    - name: Create Prometheus system user
      user:
        name: prometheus
        system: yes
        shell: /bin/false
        create_home: no
        state: present

    # Lock the Prometheus user
    - name: Lock Prometheus user
      command: usermod -L prometheus
      become: yes

    # Create necessary directories for Prometheus
    - name: Create Prometheus directories
      file:
        path: "{{ item }}"
        state: directory
        owner: prometheus
        group: prometheus
        mode: '0775'
      with_items:
        - /etc/prometheus
        - /var/lib/prometheus
      become: yes

    # Set up Prometheus systemd service
    - name: Set up Prometheus systemd service
      template:
        src: prometheus.service.j2
        dest: /etc/systemd/system/prometheus.service
      become: yes

    # Reload systemd to pick up the new Prometheus service
    - name: Reload systemd
      systemd:
        daemon_reload: yes
      become: yes

    # Start Prometheus service
    - name: Start Prometheus service
      systemd:
        name: prometheus
        state: started
        enabled: yes
      become: yes

    # Ensure Prometheus configuration file exists
    - name: Ensure Prometheus configuration file exists
      copy:
        dest: /etc/prometheus/prometheus.yml
        content: |
          global:
            scrape_interval: 15s

          scrape_configs:
            - job_name: 'prometheus'
              static_configs:
                - targets: ['localhost:9090']
        owner: prometheus
        group: prometheus
        mode: '0644'

    - name: Reload systemd and restart Prometheus
      systemd:
        name: prometheus
        state: restarted
        enabled: yes
        daemon_reload: yes
